baseURL = "https://1230pharmacy.ca"
languageCode = "en-us"
title = "My New Hugo Site"


[params]
    address = "1230 91 St SW, Unit 102"
    address2 = "Edmonton, AB, T6X 0P2"
    phone = "780-916-1230"
    fax = "780-916-3933"
    email = "info@1230pharmacy.ca"
    licenseNumber = "4030"

    [params.social]
    facebook = "https://www.facebook.com/1230-Pharmacy-106712311521954/" 