baseURL = "1230pharmacy.ca"
languageCode = "en-us"
title = "My New Hugo Site"


[params]
    address = "1230 91 St SW Unit 102"
    phone = "587 712-0072"
    fax = ""
    email = "info@1230pharmacy.ca"